<?php
const PRINT_SQL = false;

const SERVER_NAME = "";
const USERNAME = "";
const PASSWORD = "";
const DB_NAME = "";

const ITEMS_PER_BATCH = 10;
const TOTAL_BATCHES = 2;

const RS_MULTICREDIT_JAPANESE =	10;
const RS_MULTICREDIT_JAPANESE_ADVANCED =		10;
const RS_MULTICREDIT_JAPANESE_BASIC	=	1;
const RS_MULTICREDIT_JAPANESE_INTERMEDIATE	=	10;
const RS_MULTICREDIT_JAPANESE_NATIVE	=	10;
const RS_MULTICREDIT_JOBLEVEL_EXPERIENCED	=	2;
const RS_MULTICREDIT_JOBLEVEL_GRADUATE	=	1;
const RS_MULTICREDIT_JOBLEVEL_MANAGER	=	3;

